In [8]:
%pip install numpy
%pip install pandas


import numpy as np
import numpy.typing as npt
import pandas as pd


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Exercise 1 Haddamard Matrix


In [9]:

H1 = np.array([[1, 1],
               [1, -1]])

def Hadamard_unnormalized(n: int):
    if n == 0:
        return np.array([[1]])
    if n == 1:
        return H1

    return np.kron(H1, Hadamard_unnormalized(n - 1))

def Hadamard(n: int):
    unnormalized_H = Hadamard_unnormalized(n)
    normalization_factor = 1 / np.sqrt(2**n)
    return normalization_factor * unnormalized_H


for i in range(5):
    print(Hadamard(i))

[[1.]]
[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]
[[ 0.5  0.5  0.5  0.5]
 [ 0.5 -0.5  0.5 -0.5]
 [ 0.5  0.5 -0.5 -0.5]
 [ 0.5 -0.5 -0.5  0.5]]
[[ 0.35355339  0.35355339  0.35355339  0.35355339  0.35355339  0.35355339
   0.35355339  0.35355339]
 [ 0.35355339 -0.35355339  0.35355339 -0.35355339  0.35355339 -0.35355339
   0.35355339 -0.35355339]
 [ 0.35355339  0.35355339 -0.35355339 -0.35355339  0.35355339  0.35355339
  -0.35355339 -0.35355339]
 [ 0.35355339 -0.35355339 -0.35355339  0.35355339  0.35355339 -0.35355339
  -0.35355339  0.35355339]
 [ 0.35355339  0.35355339  0.35355339  0.35355339 -0.35355339 -0.35355339
  -0.35355339 -0.35355339]
 [ 0.35355339 -0.35355339  0.35355339 -0.35355339 -0.35355339  0.35355339
  -0.35355339  0.35355339]
 [ 0.35355339  0.35355339 -0.35355339 -0.35355339 -0.35355339 -0.35355339
   0.35355339  0.35355339]
 [ 0.35355339 -0.35355339 -0.35355339  0.35355339 -0.35355339  0.35355339
   0.35355339 -0.35355339]]
[[ 0.25  0.25  0.25  0.25  0.25  0.2

In [10]:
def solve_least_squares(XT_psi, y_rule):
    w_star, _, _, _ = np.linalg.lstsq(XT_psi, y_rule, rcond=None)
    y_hat = XT_psi @ w_star
    return pd.DataFrame({"Original y": y_rule, "Predicted y_hat": y_hat})

XT = np.array([
    [+1, +1, +1],
    [+1, +1, -1],
    [+1, -1, +1],
    [+1, -1, -1],
    [-1, +1, +1],
    [-1, +1, -1],
    [-1, -1, +1],
    [-1, -1, -1]
])
print(XT.shape)
y_rule_110 = np.array([+1, -1, -1, -1, +1, -1, -1, +1])

y_rule_126 = np.array([+1, -1, -1, -1, -1, -1, -1, +1])

HT = Hadamard(3) @ XT

solve_least_squares(HT, y_rule_110)


solve_least_squares(HT, y_rule_126)

(8, 3)


Original y  Predicted y_hat
0           1              0.0
1          -1             -1.0
2          -1             -1.0
3          -1              0.0
4          -1             -1.0
5          -1              0.0
6          -1              0.0
7           1              0.0

In [11]:

def self_conj(A):
    return np.conj(A) @ A

for i in range(5):
    print(self_conj(Hadamard(i)))    

[[1.]]
[[ 1.00000000e+00 -2.23711432e-17]
 [-2.23711432e-17  1.00000000e+00]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[ 1.00000000e+00 -5.59278579e-18 -5.59278579e-18 -8.28500202e-18
   2.21627898e-17 -8.28500202e-18 -2.21627898e-17 -5.59278579e-18]
 [-5.59278579e-18  1.00000000e+00 -8.28500202e-18 -5.59278579e-18
  -8.28500202e-18  2.21627898e-17 -5.59278579e-18 -2.21627898e-17]
 [-5.59278579e-18 -8.28500202e-18  1.00000000e+00 -5.59278579e-18
  -2.21627898e-17 -5.59278579e-18  2.21627898e-17 -8.28500202e-18]
 [-8.28500202e-18 -5.59278579e-18 -5.59278579e-18  1.00000000e+00
  -5.59278579e-18 -2.21627898e-17 -8.28500202e-18  2.21627898e-17]
 [ 2.21627898e-17 -8.28500202e-18 -2.21627898e-17 -5.59278579e-18
   1.00000000e+00 -5.59278579e-18 -5.59278579e-18 -8.28500202e-18]
 [-8.28500202e-18  2.21627898e-17 -5.59278579e-18 -2.21627898e-17
  -5.59278579e-18  1.00000000e+00 -8.28500202e-18 -5.59278579e-18]
 [-2.21627898e-17 -5.59278579e-18  2.21627898e-17 -8.28500202e-

findings:
Only elements on the diagonal are 1, rest is 0.
Aka we have orthonormal basis vectors here
I think this implies that its an isomorphism thus every 2^d vector can be uniquely transformed.


In [12]:
# H_dagger and H are the same since we're dealing with real values

y_110_transform = Hadamard(3) @ y_rule_110
print(y_110_transform)

XT_Hadamardtransformed = Hadamard(3) @ XT


w_star, _, _, _ = np.linalg.lstsq(XT_Hadamardtransformed, y_110_transform, rcond=None)
y_hat = XT_Hadamardtransformed @ w_star
print(pd.DataFrame({"Original y": y_110_transform, "Predicted y_hat": y_hat}))



[-0.70710678  0.70710678  0.70710678  2.12132034 -0.70710678  0.70710678
  0.70710678 -0.70710678]
   Original y  Predicted y_hat
0   -0.707107         0.000000
1    0.707107         0.707107
2    0.707107         0.707107
3    2.121320         0.000000
4   -0.707107        -0.707107
5    0.707107         0.000000
6    0.707107         0.000000
7   -0.707107         0.000000
