In [29]:
import numpy as np


In [30]:

def sierpinski_matrix(n):
    if n == 1:
        return np.array([[1, 0], [1, 1]])
    else:
        prev = sierpinski_matrix(n - 1)
        return np.kron(np.array([[1, 0], [1, 1]]), prev)

print(sierpinski_matrix(2))


[[1 0 0 0]
 [1 1 0 0]
 [1 0 1 0]
 [1 1 1 1]]


Assuming the additions and mmutiplications are defined as in exercise 2.2

In [31]:
# thanks chatgpt for implementing the 2 functions below

def boolean_matrix_vector_mult(matrix, vector):
    """
    Performs matrix-vector multiplication in Boolean algebra.
    Addition is XOR, and multiplication is binary AND.
    """
    # Ensure inputs are numpy arrays
    matrix = np.array(matrix)
    vector = np.array(vector)
    
    # Initialize the result vector with zeros
    result = np.zeros(matrix.shape[0], dtype=int)
    
    # Perform Boolean matrix-vector multiplication
    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[1]):
            # Use binary AND for multiplication and XOR for addition
            result[i] ^= matrix[i, j] & vector[j]
    
    return result

def boolean_matrix_mult(matrix1, matrix2):
    """
    Performs matrix-matrix multiplication in Boolean algebra.
    Addition is XOR, and multiplication is binary AND.
    """
    # Ensure inputs are numpy arrays
    matrix1 = np.array(matrix1)
    matrix2 = np.array(matrix2)
    
    # Initialize the result matrix with zeros
    result = np.zeros((matrix1.shape[0], matrix2.shape[1]), dtype=int)
    
    # Perform Boolean matrix-matrix multiplication using the vector function
    for j in range(matrix2.shape[1]):
        # Extract the j-th column of matrix2
        col_vector = matrix2[:, j]
        
        # Compute the j-th column of the result by matrix-vector multiplication
        result[:, j] = boolean_matrix_vector_mult(matrix1, col_vector)
    
    return result

In [32]:
for j in range(2, 6):
    s = sierpinski_matrix(j)
    s_2 = boolean_matrix_mult(s, s)
    print("Sierpinski matrix S_{}:\n".format(j), s)
    print("Boolean matrix product S_{} * S_{}:\n".format(j, j), s_2)


Sierpinski matrix S_2:
 [[1 0 0 0]
 [1 1 0 0]
 [1 0 1 0]
 [1 1 1 1]]
Boolean matrix product S_2 * S_2:
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
Sierpinski matrix S_3:
 [[1 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0]
 [1 0 1 0 0 0 0 0]
 [1 1 1 1 0 0 0 0]
 [1 0 0 0 1 0 0 0]
 [1 1 0 0 1 1 0 0]
 [1 0 1 0 1 0 1 0]
 [1 1 1 1 1 1 1 1]]
Boolean matrix product S_3 * S_3:
 [[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1]]
Sierpinski matrix S_4:
 [[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0]
 [1 0 1 0 0 0 0 0 1 0 1 0 0 0 0 0]
 [1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0]
 [1 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0]
 [1 1 0

Sierpinski Matricies multilied with itself resut in the identity matrix.
It reminds me of orthonormal matricies which can be multiplied with their transpose to create the identity matrix. Except here its not transpose ( also sierpinski is not symmetric as that would result in transpose and og matrix to be the same)

These matricies are somewhat similar to the orthonormal ones as the scalar product between a row and a column is 1 if same index. 0 else (i.e. identity matrix duh)




In [ ]:
# Define f110 and f126 as binary vectors
f110 = np.array([0, 1, 1, 1, 0, 1, 1, 0], dtype=int)
f126 = np.array([0, 1, 1, 1, 1, 1, 1, 0], dtype=int)

S3 = sierpinski_matrix(3)

w110 = boolean_matrix_vector_mult(S3, f110)
w126 = boolean_matrix_vector_mult(S3, f126)

f110_check = boolean_matrix_vector_mult(S3, w110)
f126_check = boolean_matrix_vector_mult(S3, w126)

print("w110:", w110)
print("Verification f110:", f110_check, "matches f110:", np.array_equal(f110_check, f110))

print("w126:", w126)
print("Verification f126:", f126_check, "matches f126:", np.array_equal(f126_check, f126))

w110: [0 1 1 1 0 0 0 1]
Verification f110: [0 1 1 1 0 1 1 0] matches f110: True
w126: [0 1 1 1 1 1 1 0]
Verification f126: [0 1 1 1 1 1 1 0] matches f126: True
