In [1]:


import numpy as np
import numpy.typing as npt


Exercise 1 Haddamard Matrix


In [3]:
#a)
H1 = 1 / np.sqrt(2) * np.array([[1, 1],
               [1, -1]])

def Hadamard(n: int):
    if n == 0:
        return np.array([1])
    if n == 1:
        return H1
    return np.kron(H1, Hadamard(n - 1))


for i in range(5):
    print(Hadamard(i))

[1]
[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]
[[ 0.5  0.5  0.5  0.5]
 [ 0.5 -0.5  0.5 -0.5]
 [ 0.5  0.5 -0.5 -0.5]
 [ 0.5 -0.5 -0.5  0.5]]
[[ 0.35355339  0.35355339  0.35355339  0.35355339  0.35355339  0.35355339
   0.35355339  0.35355339]
 [ 0.35355339 -0.35355339  0.35355339 -0.35355339  0.35355339 -0.35355339
   0.35355339 -0.35355339]
 [ 0.35355339  0.35355339 -0.35355339 -0.35355339  0.35355339  0.35355339
  -0.35355339 -0.35355339]
 [ 0.35355339 -0.35355339 -0.35355339  0.35355339  0.35355339 -0.35355339
  -0.35355339  0.35355339]
 [ 0.35355339  0.35355339  0.35355339  0.35355339 -0.35355339 -0.35355339
  -0.35355339 -0.35355339]
 [ 0.35355339 -0.35355339  0.35355339 -0.35355339 -0.35355339  0.35355339
  -0.35355339  0.35355339]
 [ 0.35355339  0.35355339 -0.35355339 -0.35355339 -0.35355339 -0.35355339
   0.35355339  0.35355339]
 [ 0.35355339 -0.35355339 -0.35355339  0.35355339 -0.35355339  0.35355339
   0.35355339 -0.35355339]]
[[ 0.25  0.25  0.25  0.25  0.25  0.25  

In [11]:
#b)
f_110 = np.array([+1, -1, -1, -1, +1, -1, -1, +1],dtype=float)
f_126 = np.array([+1, -1, -1, -1, -1, -1, -1, +1])

from numpy.linalg import inv



H_3 = Hadamard(3)
H_3_inv = inv(H_3)
w_110  = H_3_inv @ f_110
w_126  = H_3_inv @ f_126

print((H_3@w_110)) # f_110
print(H_3@w_126) #f_126

[ 1. -1. -1. -1.  1. -1. -1.  1.]
[ 1. -1. -1. -1.  1. -1. -1.  1.]
[False False  True  True  True  True  True  True]


In [15]:
for i in range(5):
    H = Hadamard(i)
    print(H.conj().T @ H)  

1
[[ 1.00000000e+00 -2.23711432e-17]
 [-2.23711432e-17  1.00000000e+00]]
[[ 1.00000000e+00 -1.23259516e-32 -1.23259516e-32  1.23259516e-32]
 [-1.23259516e-32  1.00000000e+00  1.23259516e-32 -1.23259516e-32]
 [-1.23259516e-32  1.23259516e-32  1.00000000e+00 -1.23259516e-32]
 [ 1.23259516e-32 -1.23259516e-32 -1.23259516e-32  1.00000000e+00]]
[[1.00000000e+00 5.90395006e-18 5.90395006e-18 7.97383775e-18
  5.90395006e-18 7.97383775e-18 2.18516256e-17 5.90395006e-18]
 [5.90395006e-18 1.00000000e+00 7.97383775e-18 5.90395006e-18
  7.97383775e-18 5.90395006e-18 5.90395006e-18 2.18516256e-17]
 [5.90395006e-18 7.97383775e-18 1.00000000e+00 5.90395006e-18
  2.18516256e-17 5.90395006e-18 5.90395006e-18 7.97383775e-18]
 [7.97383775e-18 5.90395006e-18 5.90395006e-18 1.00000000e+00
  5.90395006e-18 2.18516256e-17 7.97383775e-18 5.90395006e-18]
 [5.90395006e-18 7.97383775e-18 2.18516256e-17 5.90395006e-18
  1.00000000e+00 5.90395006e-18 5.90395006e-18 7.97383775e-18]
 [7.97383775e-18 5.90395006e-18 5

findings:
H.conj().T @ H is the 2^n x 2^n identity matrix. Therefore H are unitary matrices <=> Column and Row vectors are orthogonal and the
column vectors form a complete basis for 2^n-dim vector space. Therefore  every 2^n-dimensional vector has a Hadamard transform.


In [16]:
#b)
f_110 = np.array([+1, -1, -1, -1, +1, -1, -1, +1],dtype=float)
f_126 = np.array([+1, -1, -1, -1, -1, -1, -1, +1])




H_3 = Hadamard(3)
H_3_inv = H_3.T # because H is unitary and real
w_110  = H_3_inv @ f_110
w_126  = H_3_inv @ f_126

print((H_3@w_110)) # f_110
print(H_3@w_126) #f_126

[ 1. -1. -1. -1.  1. -1. -1.  1.]
[ 1. -1. -1. -1. -1. -1. -1.  1.]
