In [3]:
import numpy as np

def phi(x):
    # first we flip the array because the input is in reverse order
    x = np.flip(x, axis=0)
    n = len(x)
    # we create an array of 2^n elements which will be out end result
    y = np.zeros(2 ** n)
    for i in range(len(y)):
        # first we convert the index to binary with n digits
        b = np.binary_repr(i, width=n)
        # then we calculate the product of x[j] ^ b[j] for all j in range(n), which is the iths element of the result
        y[i] = np.prod([x[j] ** int(b[j]) for j in range(len(b))])
    return y

# test for 3 digits
x = np.array([1, 2, 3])
result = phi(x)
print(result)

# test for 4 digits
x = np.array([1, 2, 3, 4])
result = phi(x)
print(result)

[1. 1. 2. 2. 3. 3. 6. 6.]
[ 1.  1.  2.  2.  3.  3.  6.  6.  4.  4.  8.  8. 12. 12. 24. 24.]


**Note**: There is a very compelling solution to this task which involves the [Kronecker product](https://en.wikipedia.org/wiki/Kronecker_product) “⊗”. Yet, this solution requires creative out-of-the-box thinking. If you can discover this solution and successfully implement it using `numpy.kron`, you will be awarded **5 additional points**.


We define three new vectors:

- $\bar{x_1} = [x_1^0 x_1^1]^T$
- $\bar{x_2} = [x_2^0 x_2^1]^T$
- $\bar{x_3} = [x_3^0 x_3^1]^T$

Then we can easily calculate the **Kronecker prodruct** of $\bar{x_3}⊗\bar{x_2}⊗\bar{x_1}$ using the numpy.kron function. 

In [11]:
def kronecker_product_variable_length(x):
    x_bars = [np.array([elem**0, elem**1]).reshape(-1, 1) for elem in x]
    
    # Compute the Kronecker product starting from the last element to the first
    result = x_bars[-1]
    for x_bar in reversed(x_bars[:-1]):
        result = np.kron(result, x_bar)
    
    return result


x = np.array([1, 2, 3])
result = kronecker_product_variable_length(x)
print(f'Input x = {x}: \n {result}')

x = np.array([1, 2, 3, 4])
result = kronecker_product_variable_length(x)
print(f'\nInput x = {x}: \n {result}')

Input x = [1 2 3]: 
 [[1]
 [1]
 [2]
 [2]
 [3]
 [3]
 [6]
 [6]]

Input x = [1 2 3 4]: 
 [[ 1]
 [ 1]
 [ 2]
 [ 2]
 [ 3]
 [ 3]
 [ 6]
 [ 6]
 [ 4]
 [ 4]
 [ 8]
 [ 8]
 [12]
 [12]
 [24]
 [24]]
