Exercise 5


5.6



5.7

In [85]:
import numpy as np

# Define Pauli matrices
I = np.array([[1, 0], [0, 1]])
Z = np.array([[1, 0], [0, -1]])
X = np.array([[0, 1], [1, 0]])
Y = np.array([[0, -1j], [1j, 0]])

# Hadamard matrix H
H = (1 / np.sqrt(2)) * (X + Z)

# a) Verify X^2 = Y^2 = Z^2 = I
print("X^2:\n", np.dot(X, X))
print("Y^2:\n", np.dot(Y, Y))
print("Z^2:\n", np.dot(Z, Z))

# b) Verify -iXYZ = I
XYZ = np.dot(X, np.dot(Y, Z))
print("-iXYZ:\n", -1j * XYZ)

X^2:
 [[1 0]
 [0 1]]
Y^2:
 [[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]
Z^2:
 [[1 0]
 [0 1]]
-iXYZ:
 [[1.-0.j 0.-0.j]
 [0.-0.j 1.-0.j]]


$$
\textbf{(c) Step-by-step via equations only}
$$

$$
\text{Given: }X^2=Y^2=Z^2=I,\quad -\,i\,X\,Y\,Z=I \;\Longrightarrow\; X\,Y\,Z=i\,I.
$$

$$
\textbf{(1) } XY = iZ:
$$
$$
X\,Y\,Z = i\,I
$$
$$
X\,Y\,Z\,Z = i\,I\,Z
$$
$$
X\,Y\,I = i\,Z
$$
$$
X\,Y = i\,Z
$$

$$
\textbf{(2) } YZ = iX:
$$
$$
X\,Y\,Z = i\,I
$$
$$
X\,(X\,Y\,Z) = X\,(i\,I)
$$
$$
(X\,X)\,Y\,Z = i\,X
$$
$$
I\,Y\,Z = i\,X
$$
$$
Y\,Z = i\,X
$$

$$
\textbf{(3) } ZX = iY:
$$
$$
Y\,Z = i\,X
$$
$$
(Y\,Z)\,X = (i\,X)\,X
$$
$$
Y\,(Z\,X) = i\,(X\,X)
$$
$$
Y\,(Z\,X) = i\,I
$$
$$
(Y\,Y)\,(Z\,X) = Y\,(i\,I)
$$
$$
I\,(Z\,X) = i\,Y
$$
$$
Z\,X = i\,Y
$$

$$
\textbf{(4) } YX = -\,iZ:
$$
$$
X\,Y = i\,Z
$$
$$
Y\,(X\,Y) = Y\,(i\,Z)
$$
$$
(Y\,X)\,Y = i\,(Y\,Z)
$$
$$
\text{(from (2)}:Y\,Z = i\,X\text{)}
$$
$$
(Y\,X)\,Y = i\,(i\,X) = i^2\,X = -\,X
$$
$$
(Y\,X)\,(Y\,Y) = -\,X\,Y
$$
$$
(Y\,X)\,I = -\,X\,Y
$$
$$
Y\,X = -\,X\,Y
$$
$$
X\,Y = i\,Z
\;\Longrightarrow\;
Y\,X = -\,i\,Z
$$

$$
\textbf{(5) } ZY = -\,iX:
$$
$$
Y\,Z = i\,X
$$

$$
Z\,Y = -\,i\,X
$$

$$
\textbf{(6) } XZ = -\,iY:
$$
$$
Z\,X = i\,Y
$$

$$
X\,Z = -\,i\,Y
$$

$$
\textbf{Conclusion:}
$$

$$
XY = iZ,\quad
YZ = iX,\quad
ZX = iY,\quad
YX = -\,iZ,\quad
ZY = -\,iX,\quad
XZ = -\,iY.
$$


In [86]:
# d) Verify H X H = Z
HXH = np.dot(H, np.dot(X, H))
print("H X H = Z:\n", HXH)

H X H = Z:
 [[ 1.00000000e+00  2.23711432e-17]
 [-2.23711432e-17 -1.00000000e+00]]


Exercise 5.9

The matrix representation is built by constructing the upper left quadrant just like the identity matrix and then to add an modified variant of the bottom right quadrant.

The rows of the matrix correspond to the enumberated qbits values $|x_1 x_2\rangle$, $|01\rangle$, $|10\rangle$, $|11\rangle$, they are constructed via $x_1 \otimes x_2$

In the above representation we can see that 3rd and 4th row have been swapped.

We can do the same here and identify the rows in which the flipbit $x_2$ is 1: row 2 and 4. In row 2, $x_1$ is 0, in row 4 its 1.
For those 2 rows we can switch those and thus create the flipping operation for x_1.


\begin{bmatrix}
1 & 0 & 0 & 0 \\
0 & 0 & 0 & 1 \\
0 & 0 & 1 & 0 \\
0 & 1 & 0 & 0
\end{bmatrix}





$
\text{SWAP} = CNOT_{1 \to 2} \cdot CNOT_{2 \to 1} \cdot CNOT_{1 \to 2}
$

$
CNOT_{1 \to 2} =
\begin{pmatrix}
1 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & 0 & 1 \\
0 & 0 & 1 & 0
\end{pmatrix},
\quad
CNOT_{2 \to 1} =
\begin{pmatrix}
1 & 0 & 0 & 0 \\
0 & 0 & 0 & 1 \\
0 & 0 & 1 & 0 \\
0 & 1 & 0 & 0
\end{pmatrix}
$






\begin{pmatrix}
1 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & 0 & 1 \\
0 & 0 & 1 & 0
\end{pmatrix} 

\begin{pmatrix}
1 & 0 & 0 & 0 \\
0 & 0 & 0 & 1 \\
0 & 0 & 1 & 0 \\
0 & 1 & 0 & 0
\end{pmatrix}

\begin{pmatrix}
1 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & 0 & 1 \\
0 & 0 & 1 & 0
\end{pmatrix}
=
\begin{pmatrix}
1 & 0 & 0 & 0 \\
0 & 0 & 1 & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & 0 & 1
\end{pmatrix}

