### task 4.2 rotations in the complex plane


After euelrs identity we know that $ln(i \cdot 1) = ln(e^{\frac{\pi}{2}i} \cdot e^{2\pi i k}) = 2\pi i(\frac{1}{4}+k)$, with
$k \in \mathbb{Z}$


### task 4.3 even more cyclic groups

In [ ]:
#a)
import numpy as np

S = np.array([[1,0],[0,1j]])

print(S.conj() @ S)
#As we can see S is unitary

array([[1.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j]])

## b)


As we see $S$, with $$S = \begin{bmatrix}
1 & 0 \\
0 & i
\end{bmatrix}$$, is a diagonal matrix.
 Therefore $$S^k = \begin{bmatrix}
1^k & 0 \\
0 & i^k
\end{bmatrix}$$
Now because $$S^k\lvert 1 \rangle$$ essentially extracts $S_{22}$, we have $$S^k\lvert 1 \rangle = i^k$$. From
earlier we know that $$i^0 = 1\\ i^1 = i \\ i^2 = -1 \\ i^3 = -i\\ i^4 = 1$$



### task 4.4 complex numbers as matrices

#### 4.4 a)

In [4]:
import numpy as np

c1 = 3 + 4j
c2 = 2 - 2j

print("c1 + c2 = " + str(c1 + c2))
print("c1 * c2 = " + str(c1 * c2))
print("c1* = " +  str(c1.conjugate()))
print("|c1| = " + str(np.abs(c1)))


c1 + c2 = (5+2j)
c1 * c2 = (14+2j)
c1* = (3-4j)
|c1| = 5.0


#### 4.4 b)

In [14]:
mat_1 = np.array([[1, 0], [0, 1]])
mat_i = np.array([[0, -1], [1, 0]])
mat_c1 = c1.real * mat_1 + c1.imag * mat_i
mat_c2 = c2.real * mat_1 + c2.imag * mat_i

print("1 = ")
print(str(mat_1))
print("i = " )
print( str(mat_i))
print("c1 = " )
print( str(mat_c1))
print("c2 = " )
print( str(mat_c2))
print("c1 + c2 = " )
print( str(mat_c1 + mat_c2))
print("c1 * c2 = " )
print( str(np.matmul(mat_c1, mat_c2)))
print("c1^T = " )
print( str(mat_c1.T))
print("sqrt(det(c1)) = " )
print( str(np.sqrt(np.linalg.det(mat_c1))))

1 = 
[[1 0]
 [0 1]]
i = 
[[ 0 -1]
 [ 1  0]]
c1 = 
[[ 3. -4.]
 [ 4.  3.]]
c2 = 
[[ 2.  2.]
 [-2.  2.]]
c1 + c2 = 
[[ 5. -2.]
 [ 2.  5.]]
c1 * c2 = 
[[14. -2.]
 [ 2. 14.]]
c1^T = 
[[ 3.  4.]
 [-4.  3.]]
sqrt(det(c1)) = 
5.000000000000001


The results of matrix addition, multiplication, transposition and the square root of the determinant correspond to the results of complex addition, multiplication, conjugation and taking the absolute value, respectively.

### 4.6
#### 4.6 a) 

In [13]:
import numpy as np

mat_1 = np.array([[1, 0, 0, 0],
                  [0, 1, 0, 0],
                  [0, 0, 1, 0],
                  [0, 0, 0, 1]])

mat_i = np.array([[0, -1, 0, 0],
                  [1, 0, 0, 0],
                  [0, 0, 0, -1],
                  [0, 0, 1, 0]])

mat_j = np.array([[0, 0, -1, 0],
                  [0, 0, 0, 1],
                  [1, 0, 0, 0],
                  [0, -1, 0, 0]])

mat_k = np.array([[0, 0, 0, -1],
                  [0, 0, -1, 0],
                  [0, 1, 0, 0],
                  [1, 0, 0, 0]])

print("1 = ")
print(mat_1)
print("i = ")
print(mat_i)
print("j = ")
print(mat_j)
print("k = ")
print(mat_k)

ijk = np.matmul(np.matmul(mat_i, mat_j), mat_k)
print("ijk = ")
print(ijk)

1 = 
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
i = 
[[ 0 -1  0  0]
 [ 1  0  0  0]
 [ 0  0  0 -1]
 [ 0  0  1  0]]
j = 
[[ 0  0 -1  0]
 [ 0  0  0  1]
 [ 1  0  0  0]
 [ 0 -1  0  0]]
k = 
[[ 0  0  0 -1]
 [ 0  0 -1  0]
 [ 0  1  0  0]
 [ 1  0  0  0]]
ijk = 
[[-1  0  0  0]
 [ 0 -1  0  0]
 [ 0  0 -1  0]
 [ 0  0  0 -1]]


The result of $ijk$ is $-I_4$ which corresponds to -1 which fulfills the quaternion multiplication rule for $ijk$.

#### 4.6 b)

In [16]:
import numpy as np

mat_1 = np.array([[1, 0], [0, 1]])
mat_i = np.array([[1j, 0], [0, -1j]])
mat_j = np.array([[0, 1], [-1, 0]])
mat_k = np.array([[0, 1j], [1j, 0]])

ijk = np.matmul(np.matmul(mat_i, mat_j), mat_k)

print("1 = ")
print(mat_1)
print("i = ")
print(mat_i)
print("j = ")
print(mat_j)
print("k = ")
print(mat_k)
print("ijk = ")
print(ijk)

1 = 
[[1 0]
 [0 1]]
i = 
[[ 0.+1.j  0.+0.j]
 [ 0.+0.j -0.-1.j]]
j = 
[[ 0  1]
 [-1  0]]
k = 
[[0.+0.j 0.+1.j]
 [0.+1.j 0.+0.j]]
ijk = 
[[-1.+0.j  0.+0.j]
 [ 0.+0.j -1.+0.j]]


The result of $ijk$ is $-I_2$ which corresponds to -1 which fulfills the quaternion multiplication rule for $ijk$.

In [18]:
# Define the complete set of quaternion elements as 2x2 complex matrices
quaternion_set = {
    "1": mat_1,
    "-1": -mat_1,
    "i": mat_i,
    "-i": -mat_i,
    "j": mat_j,
    "-j": -mat_j,
    "k": mat_k,
    "-k": -mat_k,
}

# List of quaternion labels
labels = list(quaternion_set.keys())

# Initialize an empty result table
cayley_table = []

# Compute the Cayley table by pairwise multiplication
for row_label in labels:
    row = []
    for col_label in labels:
        # Multiply the corresponding matrices
        result = np.dot(quaternion_set[row_label], quaternion_set[col_label])
        # Match the result to a quaternion symbol in the set
        for key, value in quaternion_set.items():
            if np.allclose(result, value):  # Check matrix equality
                row.append(key)
                break
    cayley_table.append(row)

# Display the Cayley table
labels, cayley_table


(['1', '-1', 'i', '-i', 'j', '-j', 'k', '-k'],
 [['1', '-1', 'i', '-i', 'j', '-j', 'k', '-k'],
  ['-1', '1', '-i', 'i', '-j', 'j', '-k', 'k'],
  ['i', '-i', '-1', '1', 'k', '-k', '-j', 'j'],
  ['-i', 'i', '1', '-1', '-k', 'k', 'j', '-j'],
  ['j', '-j', '-k', 'k', '-1', '1', 'i', '-i'],
  ['-j', 'j', 'k', '-k', '1', '-1', '-i', 'i'],
  ['k', '-k', 'j', '-j', '-i', 'i', '-1', '1'],
  ['-k', 'k', '-j', 'j', 'i', '-i', '1', '-1']])

$Q_8$ does not seem to be an Abelian Group because the Cayley table is not symmetric.

## task 4.7: vector Logic (10 Points)

Vector logic was developed by the Uruguayan mathematician Eduardo Mizraji. Following his framework, we represent the two truth values `false` and `true` as orthonormal vectors:

$$
\text{false} \equiv n =
\begin{bmatrix}
1 \\
0
\end{bmatrix}
\quad \text{("no")}
$$

$$
\text{true} \equiv s =
\begin{bmatrix}
0 \\
1
\end{bmatrix}
\quad \text{("si")}
$$

Now, to further explore Mizraji's framework, we first of all need to recall that the `outer product` $xy^T$ of two vectors $x \in \mathbb{R}^m$ and $y\in \mathbb{R}^n$ produces a matrix $Z \in \mathbb{R}^{m \times n}$ such that 
$$
xy^T = Z = 
\begin{bmatrix}
x_1\,y_1 & x_1\,y_2 & \cdots & x_1\,y_n \\
x_2\,y_1 & x_2\,y_2 & \cdots & x_2\,y_n \\
\vdots & \vdots & \ddots & \vdots \\
x_m\,y_1 & x_m\,y_2 & \cdots & x_m\,y_n
\end{bmatrix}
$$
Second of all, we need to recall that the `Kronecker product` $x\otimes y$ of two vectors $x \in \mathbb{R}^m$ and $y \in \mathbb{R}^n$ produces a vector $z \in \mathbb{R}^{m n}$ such that
$$
x \otimes y = z = 
\begin{bmatrix}
x_1\,y \\ x_2\,y \\ \vdots \\ x_m\,y
\end{bmatrix}
$$

In [2]:
import numpy as np

vecN = np.array([[1], [0]])
vecS = np.array([[0], [1]])

### (a) [4 Points]
Compute the two matrices $C$ and $D$:

$$
C = n[n \otimes n]^T + n[n \otimes s]^T + n[s \otimes n]^T + s[s \otimes s]^T
$$

$$
D = n[n \otimes n]^T + s[n \otimes s]^T + s[s \otimes n]^T + s[s \otimes s]^T
$$


In [7]:
matC = np.outer(vecN, np.kron(vecN, vecN)) + \
        np.outer(vecN, np.kron(vecN, vecS)) + \
        np.outer(vecN, np.kron(vecS, vecN)) + \
        np.outer(vecS, np.kron(vecS, vecS))

matD = np.outer(vecN, np.kron(vecN, vecN)) + \
        np.outer(vecS, np.kron(vecN, vecS)) + \
        np.outer(vecS, np.kron(vecS, vecN)) + \
        np.outer(vecS, np.kron(vecS, vecS))

print(f'Matrix C: \n {matC}')
print(f'\nMatrix D: \n {matD}')

Matrix C: 
 [[1 1 1 0]
 [0 0 0 1]]

Matrix D: 
 [[1 0 0 0]
 [0 1 1 1]]


### (b) [4 Points]
Given the matrices $C$ and $D$, consider two vectors $x_1, x_2 \in \{n, s\}$ and compute the results of the functions:

$$
f_C(x_1, x_2) = C[x_1 \otimes x_2]
$$

$$
f_D(x_1, x_2) = D[x_1 \otimes x_2]
$$

In [18]:
# Define a general function to compute f for any given matrix M
def f(M, x1, x2):
    return M @ np.kron(x1, x2)

# Compute the results for all combinations of x1, x2 in {n, s}
x_values = [(vecN, vecN), (vecN, vecS), (vecS, vecN), (vecS, vecS)]

print("\nResults for f_C:")
for x1, x2 in x_values:
    result = f(matC, x1, x2)
    print(f"f_C({x1.T}, {x2.T}) = {result.T}")

print("\nResults for f_D:")
for x1, x2 in x_values:
    result = f(matD, x1, x2)
    print(f"f_D({x1.T}, {x2.T}) = {result.T}")


Results for f_C:
f_C([[1 0]], [[1 0]]) = [[1 0]]
f_C([[1 0]], [[0 1]]) = [[1 0]]
f_C([[0 1]], [[1 0]]) = [[1 0]]
f_C([[0 1]], [[0 1]]) = [[0 1]]

Results for f_D:
f_D([[1 0]], [[1 0]]) = [[1 0]]
f_D([[1 0]], [[0 1]]) = [[0 1]]
f_D([[0 1]], [[1 0]]) = [[0 1]]
f_D([[0 1]], [[0 1]]) = [[0 1]]


Looking at your results, which Boolean (logic) functions would you
say do  $f_C$ and $f_D$ represent?

Note that $n=[1 \ 0]$ represents the boolean value false and $s=[0 \ 1]$ true. Then:

- $f_C$ represents the `AND` logic function.
- $f_D$ represents the `OR` logic function.

### (c) [2 Points]
In order to explore whether your results are dependent on our particular choices for $n$ and $s$, repeat the above procedure but this time with the vectors

$$
n = 
\begin{bmatrix}
1 \\
0 \\
0
\end{bmatrix}, \quad s =
\begin{bmatrix}
0 \\
0 \\
1
\end{bmatrix}
$$

For the fun of it, repeat the above procedure two more times, first using

$$
n = \frac{1}{\sqrt{2}}
\begin{bmatrix}
+1 \\
-1
\end{bmatrix}, \quad s = \frac{1}{\sqrt{2}}
\begin{bmatrix}
+1 \\
+1
\end{bmatrix}
$$

and then 

$$
n = \frac{1}{\sqrt{2}}
\begin{bmatrix}
+i \\
-i
\end{bmatrix}, \quad s = \frac{1}{\sqrt{2}}
\begin{bmatrix}
+i \\
+i
\end{bmatrix}
$$

In [15]:
def compute_C_D(n, s):
    n_otimes_n = np.kron(n, n)
    n_otimes_s = np.kron(n, s)
    s_otimes_n = np.kron(s, n)
    s_otimes_s = np.kron(s, s)

    C = n @ n_otimes_n.T + n @ n_otimes_s.T + n @ s_otimes_n.T + s @ s_otimes_s.T
    D = n @ n_otimes_n.T + s @ n_otimes_s.T + s @ s_otimes_n.T + s @ s_otimes_s.T
    
    return C, D

def evaluate_logic(n, s):
    C, D = compute_C_D(n, s)

    print("\nMatrix C:\n", C)
    print("\nMatrix D:\n", D)

    x_values = [(n, n), (n, s), (s, n), (s, s)]

    print("\nResults for f_C:")
    for x1, x2 in x_values:
        result = f(C, x1, x2)
        print(f"f_C({x1.T}, {x2.T}) = {result.T}")

    print("\nResults for f_D:")
    for x1, x2 in x_values:
        result = f(D, x1, x2)
        print(f"f_D({x1.T}, {x2.T}) = {result.T}")

In [12]:
# 1
n1 = np.array([[1], [0], [0]])
s1 = np.array([[0], [0], [1]])
evaluate_logic(n1, s1)


Matrix C:
 [[1 0 1 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1]]

Matrix D:
 [[1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 1 0 1]]

Results for f_C:
f_C([[1 0 0]], [[1 0 0]]) = [[1 0 0]]
f_C([[1 0 0]], [[0 0 1]]) = [[1 0 0]]
f_C([[0 0 1]], [[1 0 0]]) = [[1 0 0]]
f_C([[0 0 1]], [[0 0 1]]) = [[0 0 1]]

Results for f_D:
f_D([[1 0 0]], [[1 0 0]]) = [[1 0 0]]
f_D([[1 0 0]], [[0 0 1]]) = [[0 0 1]]
f_D([[0 0 1]], [[1 0 0]]) = [[0 0 1]]
f_D([[0 0 1]], [[0 0 1]]) = [[0 0 1]]


In [13]:
# 2
n2 = (1 / np.sqrt(2)) * np.array([[1], [-1]])
s2 = (1 / np.sqrt(2)) * np.array([[1], [1]])
evaluate_logic(n2, s2)


Matrix C:
 [[ 1.41421356  0.          0.          0.        ]
 [-0.70710678  0.70710678  0.70710678  0.70710678]]

Matrix D:
 [[ 1.41421356  0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678 -0.70710678]]

Results for f_C:
f_C([[ 0.70710678 -0.70710678]], [[ 0.70710678 -0.70710678]]) = [[ 0.70710678 -0.70710678]]
f_C([[ 0.70710678 -0.70710678]], [[0.70710678 0.70710678]]) = [[ 0.70710678 -0.70710678]]
f_C([[0.70710678 0.70710678]], [[ 0.70710678 -0.70710678]]) = [[ 0.70710678 -0.70710678]]
f_C([[0.70710678 0.70710678]], [[0.70710678 0.70710678]]) = [[0.70710678 0.70710678]]

Results for f_D:
f_D([[ 0.70710678 -0.70710678]], [[ 0.70710678 -0.70710678]]) = [[ 0.70710678 -0.70710678]]
f_D([[ 0.70710678 -0.70710678]], [[0.70710678 0.70710678]]) = [[0.70710678 0.70710678]]
f_D([[0.70710678 0.70710678]], [[ 0.70710678 -0.70710678]]) = [[0.70710678 0.70710678]]
f_D([[0.70710678 0.70710678]], [[0.70710678 0.70710678]]) = [[0.70710678 0.70710678]]


In [14]:
# 3
n3 = (1 / np.sqrt(2)) * np.array([[1j], [-1j]])
s3 = (1 / np.sqrt(2)) * np.array([[1j], [1j]])
print("\nEvaluating logic for third set of vectors (complex n and s):")
evaluate_logic(n3, s3)


Evaluating logic for third set of vectors (complex n and s):

Matrix C:
 [[0.-1.41421356j 0.+0.j         0.+0.j         0.+0.j        ]
 [0.+0.70710678j 0.-0.70710678j 0.-0.70710678j 0.-0.70710678j]]

Matrix D:
 [[0.-1.41421356j 0.+0.j         0.+0.j         0.+0.j        ]
 [0.-0.70710678j 0.-0.70710678j 0.-0.70710678j 0.+0.70710678j]]

Results for f_C:
f_C([[0.+0.70710678j 0.-0.70710678j]], [[0.+0.70710678j 0.-0.70710678j]]) = [[0.+0.70710678j 0.-0.70710678j]]
f_C([[0.+0.70710678j 0.-0.70710678j]], [[0.+0.70710678j 0.+0.70710678j]]) = [[0.+0.70710678j 0.-0.70710678j]]
f_C([[0.+0.70710678j 0.+0.70710678j]], [[0.+0.70710678j 0.-0.70710678j]]) = [[0.+0.70710678j 0.-0.70710678j]]
f_C([[0.+0.70710678j 0.+0.70710678j]], [[0.+0.70710678j 0.+0.70710678j]]) = [[0.+0.70710678j 0.+0.70710678j]]

Results for f_D:
f_D([[0.+0.70710678j 0.-0.70710678j]], [[0.+0.70710678j 0.-0.70710678j]]) = [[0.+0.70710678j 0.-0.70710678j]]
f_D([[0.+0.70710678j 0.-0.70710678j]], [[0.+0.70710678j 0.+0.70710678j]]) 

What do you observe? Does the representation of `false / no` and `true / si` impact the logic of the results produced by this method? What would happen if $n$ and $s$ were not orthonormal?

1. 3-dimensional n and s (still representing si and no):
    - n and s are still orthonormal basis vectors
    - analogous to `false` and `true` the function $f_C$ and $f_D$ still behaved similarly to the `AND` and `OR` logic

2. 2D normalized vectors:
    - the behavior of $f_C$ and $f_D$ continued to resemble the `AND` and `OR` operations respectively
    - this indicates that as long as the vectors are orthonormal, the exact values do not significantly impact the type of logic operation represented

3. Complex $n$ and $s$:
    - $f_C$ and $f_D$ are still consistent with `AND` and `OR`

Conlusion:
- Dimensionality of the representation of `false` and `true` does not impact the logic as long as $n$ and $s$ remain orthonormal
- Orthonormal vectors ensure that the Kronecker product and subsequent operations can clearly separate the contributions of `true` and `false` values in the matrices $C$ and $D$
- Normalization ensures that the magnitude of the vectors is consistent, which helps in preserving the interpretation of the logic functions as binary outcomes
- If $n$ and $s$ are not orthonormal, the distinction between true and false becomes ambiguous, and the results may not clearly correspond to logical operations