### task 4.4 complex numbers as matrices

#### 4.4 a)

In [4]:
import numpy as np

c1 = 3 + 4j
c2 = 2 - 2j

print("c1 + c2 = " + str(c1 + c2))
print("c1 * c2 = " + str(c1 * c2))
print("c1* = " +  str(c1.conjugate()))
print("|c1| = " + str(np.abs(c1)))


c1 + c2 = (5+2j)
c1 * c2 = (14+2j)
c1* = (3-4j)
|c1| = 5.0


#### 4.4 b)

In [14]:
mat_1 = np.array([[1, 0], [0, 1]])
mat_i = np.array([[0, -1], [1, 0]])
mat_c1 = c1.real * mat_1 + c1.imag * mat_i
mat_c2 = c2.real * mat_1 + c2.imag * mat_i

print("1 = ")
print(str(mat_1))
print("i = " )
print( str(mat_i))
print("c1 = " )
print( str(mat_c1))
print("c2 = " )
print( str(mat_c2))
print("c1 + c2 = " )
print( str(mat_c1 + mat_c2))
print("c1 * c2 = " )
print( str(np.matmul(mat_c1, mat_c2)))
print("c1^T = " )
print( str(mat_c1.T))
print("sqrt(det(c1)) = " )
print( str(np.sqrt(np.linalg.det(mat_c1))))

1 = 
[[1 0]
 [0 1]]
i = 
[[ 0 -1]
 [ 1  0]]
c1 = 
[[ 3. -4.]
 [ 4.  3.]]
c2 = 
[[ 2.  2.]
 [-2.  2.]]
c1 + c2 = 
[[ 5. -2.]
 [ 2.  5.]]
c1 * c2 = 
[[14. -2.]
 [ 2. 14.]]
c1^T = 
[[ 3.  4.]
 [-4.  3.]]
sqrt(det(c1)) = 
5.000000000000001


The results of matrix addition, multiplication, transposition and the square root of the determinant correspond to the results of complex addition, multiplication, conjugation and taking the absolute value, respectively.

### 4.6
#### 4.6 a) 

In [13]:
import numpy as np

mat_1 = np.array([[1, 0, 0, 0],
                  [0, 1, 0, 0],
                  [0, 0, 1, 0],
                  [0, 0, 0, 1]])

mat_i = np.array([[0, -1, 0, 0],
                  [1, 0, 0, 0],
                  [0, 0, 0, -1],
                  [0, 0, 1, 0]])

mat_j = np.array([[0, 0, -1, 0],
                  [0, 0, 0, 1],
                  [1, 0, 0, 0],
                  [0, -1, 0, 0]])

mat_k = np.array([[0, 0, 0, -1],
                  [0, 0, -1, 0],
                  [0, 1, 0, 0],
                  [1, 0, 0, 0]])

print("1 = ")
print(mat_1)
print("i = ")
print(mat_i)
print("j = ")
print(mat_j)
print("k = ")
print(mat_k)

ijk = np.matmul(np.matmul(mat_i, mat_j), mat_k)
print("ijk = ")
print(ijk)

1 = 
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
i = 
[[ 0 -1  0  0]
 [ 1  0  0  0]
 [ 0  0  0 -1]
 [ 0  0  1  0]]
j = 
[[ 0  0 -1  0]
 [ 0  0  0  1]
 [ 1  0  0  0]
 [ 0 -1  0  0]]
k = 
[[ 0  0  0 -1]
 [ 0  0 -1  0]
 [ 0  1  0  0]
 [ 1  0  0  0]]
ijk = 
[[-1  0  0  0]
 [ 0 -1  0  0]
 [ 0  0 -1  0]
 [ 0  0  0 -1]]


The result of $ijk$ is $-I_4$ which corresponds to -1 which fulfills the quaternion multiplication rule for $ijk$.

#### 4.6 b)

In [16]:
import numpy as np

mat_1 = np.array([[1, 0], [0, 1]])
mat_i = np.array([[1j, 0], [0, -1j]])
mat_j = np.array([[0, 1], [-1, 0]])
mat_k = np.array([[0, 1j], [1j, 0]])

ijk = np.matmul(np.matmul(mat_i, mat_j), mat_k)

print("1 = ")
print(mat_1)
print("i = ")
print(mat_i)
print("j = ")
print(mat_j)
print("k = ")
print(mat_k)
print("ijk = ")
print(ijk)

1 = 
[[1 0]
 [0 1]]
i = 
[[ 0.+1.j  0.+0.j]
 [ 0.+0.j -0.-1.j]]
j = 
[[ 0  1]
 [-1  0]]
k = 
[[0.+0.j 0.+1.j]
 [0.+1.j 0.+0.j]]
ijk = 
[[-1.+0.j  0.+0.j]
 [ 0.+0.j -1.+0.j]]


The result of $ijk$ is $-I_2$ which corresponds to -1 which fulfills the quaternion multiplication rule for $ijk$.

In [18]:
# Define the complete set of quaternion elements as 2x2 complex matrices
quaternion_set = {
    "1": mat_1,
    "-1": -mat_1,
    "i": mat_i,
    "-i": -mat_i,
    "j": mat_j,
    "-j": -mat_j,
    "k": mat_k,
    "-k": -mat_k,
}

# List of quaternion labels
labels = list(quaternion_set.keys())

# Initialize an empty result table
cayley_table = []

# Compute the Cayley table by pairwise multiplication
for row_label in labels:
    row = []
    for col_label in labels:
        # Multiply the corresponding matrices
        result = np.dot(quaternion_set[row_label], quaternion_set[col_label])
        # Match the result to a quaternion symbol in the set
        for key, value in quaternion_set.items():
            if np.allclose(result, value):  # Check matrix equality
                row.append(key)
                break
    cayley_table.append(row)

# Display the Cayley table
labels, cayley_table


(['1', '-1', 'i', '-i', 'j', '-j', 'k', '-k'],
 [['1', '-1', 'i', '-i', 'j', '-j', 'k', '-k'],
  ['-1', '1', '-i', 'i', '-j', 'j', '-k', 'k'],
  ['i', '-i', '-1', '1', 'k', '-k', '-j', 'j'],
  ['-i', 'i', '1', '-1', '-k', 'k', 'j', '-j'],
  ['j', '-j', '-k', 'k', '-1', '1', 'i', '-i'],
  ['-j', 'j', 'k', '-k', '1', '-1', '-i', 'i'],
  ['k', '-k', 'j', '-j', '-i', 'i', '-1', '1'],
  ['-k', 'k', '-j', 'j', 'i', '-i', '1', '-1']])

$Q_8$ does not seem to be an Abelian Group because the Cayley table is not symmetric.